config/routes.rb
Rails.application.routes.draw do
  resources :inputs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/input.rb
class Input < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :set_input, only: [:show, :edit, :update, :destroy]

  # GET /inputs
  # GET /inputs.json
  def index
    @inputs = Input.all
  end

  # GET /inputs/1
  # GET /inputs/1.json
  def show
  end

  # GET /inputs/new
  def new
    @input = Input.new
  end

  # GET /inputs/1/edit
  def edit
  end

  # POST /inputs
  # POST /inputs.json
  def create
    @input = Input.new(input_params)

    respond_to do |format|
      if @input.save
        format.html { redirect_to @input, notice: 'Input was successfully created.' }
        format.json { render :show, status: :created, location: @input }
      else
        format.html { render :new }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputs/1
  # PATCH/PUT /inputs/1.json
  def update
    respond_to do |format|
      if @input.update(input_params)
        format.html { redirect_to @input, notice: 'Input was successfully updated.' }
        format.json { render :show, status: :ok, location: @input }
      else
        format.html { render :edit }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/1
  # DELETE /inputs/1.json
  def destroy
    @input.destroy
    respond_to do |format|
      format.html { redirect_to inputs_url, notice: 'Input was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input
      @input = Input.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def input_params
      params.require(:input).permit(:name, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/views/inputs/_form.html.erb
<%= form_for(input) do |f| %>
  <% if input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(input.errors.count, "error") %> prohibited this input from being saved:</h2>

      <ul>
      <% input.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :deadline %>
    <%= f.date_select :deadline, discard_year: true, include_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inputs/edit.html.erb
<h1>Editing Input</h1>

<%= render 'form', input: @input %>

<%= link_to 'Show', @input %> |
<%= link_to 'Back', inputs_path %>

app/views/inputs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inputs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inputs.each do |input| %>
      <tr>
        <td><%= input.name %></td>
        <td><%= input.deadline %></td>
        <td><%= link_to 'Show', input %></td>
        <td><%= link_to 'Edit', edit_input_path(input) %></td>
        <td><%= link_to 'Destroy', input, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Input', new_input_path %>

app/views/inputs/new.html.erb
<h1>New Input</h1>

<%= render 'form', input: @input %>

<%= link_to 'Back', inputs_path %>

app/views/inputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @input.name %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @input.deadline %>
</p>

<%= link_to 'Edit', edit_input_path(@input) %> |
<%= link_to 'Back', inputs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestDateApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>